#!/usr/bin/env bash
# fizzbuzz

for ((i = 1; i < 100; i++)); do
        case $((i % 3))$((i % 5)) in
                00)
                        echo "FizzBuzz"
                        ;;
                0*)
                        echo "Fizz"
                        ;;
                *0)
                        echo "Buzz"
                        ;;
                *)
                        echo "'$i'"
        esac
done
