#!/usr/bin/env bash

#This script displays:
#+ The content of the current directory
#+ In a list format
#+ Where only the part of the name after the first
#+ dash is displayed (refer to the example)

for file in *; do
	if [ -f "$file" ]; then
		newname=$(echo "$file" | sed -E 's/^[^-]+-//')
		echo "$newname"
	fi
done
